### ISSUE TITLE
RZXCalibrationBuilder parameter changed in the new package

### ISSUE THREAD

**Issue by ameymeher** [PicksPeng/SimuQ#30]
Hi, I''m getting this error in this step:

prog = comp(
    backend,
    layout,
    sol_gvars,
    boxes,
    edges,
    use_pulse=use_pulse,
)

Error message:
TypeError: RZXCalibrationBuilder.__init__() got an unexpected keyword argument 'qubit_channel_mapping'

It seems the new class does not have this parameter in the init function

**Comment by liupengy19** [comment]
Hi, this is due to an API change in qiskit. We have fixed this bug in the 0.3.0 branch. You can install this branch or downgrade your Qiskit. Thank you!
