### ISSUE TITLE
qiskit-ibmq-provider is not maintiained anymore

### ISSUE THREAD

**Issue by 1ucian0** [PicksPeng/SimuQ#35]
Consider transition from `qiskit-ibmq-provider` to `qiskit-ibm-runtime` as the first one is not maintained since July 2023 https://github.com/Qiskit/qiskit-ibmq-provider

https://github.com/PicksPeng/SimuQ/blob/81d4a6d39d38ad6878d599e0f3b65797fb17ced6/setup.py#L36

**Comment by PicksPeng** [comment]
We migrated to `qiskit-ibm-runtime` in PR #38 .
